import { MenuItem, SpecialOffer, Review } from './types';

// Curated high quality food photography for categories
const CATEGORY_IMAGES: { [key: string]: string } = {
  "VEGETABLES": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&q=80&w=600",
  "SPECIAL THALI": "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&q=80&w=600",
  "TANDOOR SE": "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=600",
  "APPETIZERS": "https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&q=80&w=600",
  "SOUP": "https://images.unsplash.com/photo-1547592165-e1d17fed6005?auto=format&fit=crop&q=80&w=600",
  "BEVERAGES": "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=600",
  "MOMOS": "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&q=80&w=600",
  "CHILLY SPECIALS": "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&q=80&w=600",
  "NOODLES": "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&q=80&w=600",
  "RICE": "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&q=80&w=600",
  "DAL": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=600",
  "ROTI & NAAN": "https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?auto=format&fit=crop&q=80&w=600",
};

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  // 1. VEGETABLES
  {
    id: "v1",
    name: "Paneer Butter Masala",
    category: "VEGETABLES",
    price: 210,
    isVeg: true,
    isBestSeller: true,
    rating: 4.8,
    reviewsCount: 142,
    imageUrl: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&q=80&w=600",
    description: "Rich, creamy, and mildly sweet gravy loaded with hand-cut cubes of fresh cottage cheese and pure white butter.",
    prepTime: "15 mins"
  },
  {
    id: "v2",
    name: "Paneer Kadhai",
    category: "VEGETABLES",
    price: 220,
    isVeg: true,
    isBestSeller: false,
    rating: 4.6,
    reviewsCount: 88,
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=600",
    description: "Fresh cottage cheese cooked in a rich base of diced bell peppers, tomatoes, onions, and freshly ground kadhai spices.",
    prepTime: "18 mins"
  },
  {
    id: "v3",
    name: "Paneer Do Pyaza",
    category: "VEGETABLES",
    price: 210,
    isVeg: true,
    isBestSeller: false,
    rating: 4.5,
    reviewsCount: 64,
    imageUrl: "https://images.unsplash.com/photo-1613292443284-8d10ef9383fe?auto=format&fit=crop&q=80&w=600",
    description: "Cottage cheese chunks cooked with double-style onions in a spicy, seasoned cashew tomato sauce.",
    prepTime: "15 mins"
  },
  {
    id: "v4",
    name: "Mutter Paneer",
    category: "VEGETABLES",
    price: 200,
    isVeg: true,
    isBestSeller: false,
    rating: 4.4,
    reviewsCount: 79,
    imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=600",
    description: "Traditional North Indian comfort curry featuring sweet garden peas and fresh cottage cheese paneer cubes.",
    prepTime: "12 mins"
  },
  {
    id: "v5",
    name: "Shahi Paneer",
    category: "VEGETABLES",
    price: 240,
    isVeg: true,
    isBestSeller: true,
    rating: 4.9,
    reviewsCount: 156,
    imageUrl: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=600",
    description: "A royal preparations of cottage cheese steeped in an ultra-luxurious, golden almond-cashew cream gravy.",
    prepTime: "15 mins"
  },
  {
    id: "v6",
    name: "Paneer Tikka Masala",
    category: "VEGETABLES",
    price: 260,
    isVeg: true,
    isBestSeller: true,
    rating: 4.9,
    reviewsCount: 210,
    imageUrl: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=600",
    description: "Skewered, clay-oven roasted cottage cheese tikka tossed inside our signature house special tomato-butter masala.",
    prepTime: "20 mins"
  },
  {
    id: "v7",
    name: "Soya Chaap Masala",
    category: "VEGETABLES",
    price: 200,
    isVeg: true,
    isBestSeller: false,
    rating: 4.3,
    reviewsCount: 52,
    imageUrl: "https://images.unsplash.com/photo-1585938338392-50a59970d2ee?auto=format&fit=crop&q=80&w=600",
    description: "Succulent, marinated soybean chops simmered in a semi-dry premium onion tomato masala layout.",
    prepTime: "15 mins"
  },
  {
    id: "v8",
    name: "Boil Soy Masala",
    category: "VEGETABLES",
    price: 220,
    isVeg: true,
    isBestSeller: false,
    rating: 4.2,
    reviewsCount: 38,
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=600",
    description: "Healthy steamed soy proteins simmered in spices, low-oil base, packed with premium proteins.",
    prepTime: "12 mins"
  },
  {
    id: "v9",
    name: "Mix Veg",
    category: "VEGETABLES",
    price: 220,
    isVeg: true,
    isBestSeller: false,
    rating: 4.4,
    reviewsCount: 71,
    imageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&q=80&w=600",
    description: "A combination of seasoned market-fresh beans, carrots, cauliflower, potatoes, and peas sautéed to perfection.",
    prepTime: "12 mins"
  },
  {
    id: "v10",
    name: "Special Mix Veg",
    category: "VEGETABLES",
    price: 250,
    isVeg: true,
    isBestSeller: true,
    rating: 4.8,
    reviewsCount: 95,
    imageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&q=80&w=600",
    description: "Royal mix of garden vegetables, cottage cheese, and roasted cashew nuts with the Bawarchi premium cream finish.",
    prepTime: "15 mins"
  },
  {
    id: "v11",
    name: "Malai Kofta",
    category: "VEGETABLES",
    price: 250,
    isVeg: true,
    isBestSeller: true,
    rating: 4.8,
    reviewsCount: 112,
    imageUrl: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&q=80&w=600",
    description: "Melt-in-your-mouth minced potato and paneer deep-fried cheese balls served inside an aromatic golden cashew gravy.",
    prepTime: "17 mins"
  },
  {
    id: "v12",
    name: "Potato And Pyaza",
    category: "VEGETABLES",
    price: 160,
    isVeg: true,
    isBestSeller: false,
    rating: 4.2,
    reviewsCount: 33,
    imageUrl: "https://images.unsplash.com/photo-1518013431117-eb1465fa5752?auto=format&fit=crop&q=80&w=600",
    description: "Local Bihari styled crisp potatoes prepared with high-caramel onions and authentic rustic spices.",
    prepTime: "10 mins"
  },
  {
    id: "v13",
    name: "Aloo Dum",
    category: "VEGETABLES",
    price: 150,
    isVeg: true,
    isBestSeller: false,
    rating: 4.3,
    reviewsCount: 46,
    imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=600",
    description: "Perfect baby potatoes slow-cooked in a tangy yogurt tomato broth, finished with fresh coriander.",
    prepTime: "15 mins"
  },
  {
    id: "v14",
    name: "Aloo Kadhai",
    category: "VEGETABLES",
    price: 160,
    isVeg: true,
    isBestSeller: false,
    rating: 4.1,
    reviewsCount: 28,
    imageUrl: "https://images.unsplash.com/photo-1518013431117-eb1465fa5752?auto=format&fit=crop&q=80&w=600",
    description: "Crisp potato cubes cooked with home-pounded coriander seeds and dry red chilies in a kadhai layout.",
    prepTime: "12 mins"
  },
  {
    id: "v15",
    name: "Veg Jhalfrezi",
    category: "VEGETABLES",
    price: 190,
    isVeg: true,
    isBestSeller: false,
    rating: 4.4,
    reviewsCount: 48,
    imageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&q=80&w=600",
    description: "Semi-dry spicy stir-fry dish featuring crisp peppers, baby corn, green beans in highly tangy tomato-onion syrup.",
    prepTime: "12 mins"
  },
  {
    id: "v16",
    name: "Aloo Matar",
    category: "VEGETABLES",
    price: 150,
    isVeg: true,
    isBestSeller: false,
    rating: 4.2,
    reviewsCount: 41,
    imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=600",
    description: "Homestyle delicious comforting combination of potatoes and sweet peas in light cumin tomato spices.",
    prepTime: "11 mins"
  },
  {
    id: "v17",
    name: "Mushroom Masala",
    category: "VEGETABLES",
    price: 220,
    isVeg: true,
    isBestSeller: true,
    rating: 4.7,
    reviewsCount: 104,
    imageUrl: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&q=80&w=600",
    description: "Slices of premium white button mushrooms tossed with spicy, aromatic, semi-dry brown onion masala gravy.",
    prepTime: "15 mins"
  },
  {
    id: "v18",
    name: "Mushroom Kadhai",
    category: "VEGETABLES",
    price: 220,
    isVeg: true,
    isBestSeller: false,
    rating: 4.6,
    reviewsCount: 76,
    imageUrl: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&q=80&w=600",
    description: "Plump fresh mushrooms cooked with colorful bell peppers, roasted onions, crushed kadhai masala seasonings.",
    prepTime: "15 mins"
  },
  {
    id: "v19",
    name: "Green Peas Masala",
    category: "VEGETABLES",
    price: 200,
    isVeg: true,
    isBestSeller: false,
    rating: 4.3,
    reviewsCount: 39,
    imageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&q=80&w=600",
    description: "Green garden peas cooked in rich tomato cashew base spiced gently, topped with pure cream.",
    prepTime: "12 mins"
  },
  {
    id: "v20",
    name: "Tawa Veg (Bawarchi Special)",
    category: "VEGETABLES",
    price: 250,
    isVeg: true,
    isBestSeller: true,
    rating: 4.9,
    reviewsCount: 168,
    imageUrl: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&q=80&w=600",
    description: "Our prized signature! Tandoor-grilled vegetables, cheese, baby corn seared on iron griddle plates with butter and fresh green herbs.",
    prepTime: "18 mins"
  },
  {
    id: "v21",
    name: "Mushroom Do Pyaza",
    category: "VEGETABLES",
    price: 210,
    isVeg: true,
    isBestSeller: false,
    rating: 4.5,
    reviewsCount: 61,
    imageUrl: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&q=80&w=600",
    description: "Button mushrooms paired with double caramelised red onions inside rich ground cardamom tomato masala.",
    prepTime: "14 mins"
  },

  // 2. SPECIAL THALI
  {
    id: "th1",
    name: "Special Thali",
    category: "SPECIAL THALI",
    price: 210,
    isVeg: true,
    isBestSeller: true,
    rating: 4.9,
    reviewsCount: 420,
    imageUrl: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&q=80&w=600",
    description: "The ultimate royal Indian dining experience. Includes: 2 Butter Roti / 1 Butter Naan, roasted papad, creamy Dal Makhani, fresh Mix Veg, paneer Butter Masala, aromatic Jeera Rice, and side salad.",
    prepTime: "15 mins"
  },

  // 3. TANDOOR SE
  {
    id: "t1",
    name: "Paneer Tikka",
    category: "TANDOOR SE",
    price: 240,
    isVeg: true,
    isBestSeller: true,
    rating: 4.8,
    reviewsCount: 121,
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=600",
    description: "Cottage cheese chunks heavily marinated in charcoal yogurt spices, skewered with onions and roasted crisp in raw clay oven.",
    prepTime: "15 mins"
  },
  {
    id: "t2",
    name: "Hara Bhara Kebab",
    category: "TANDOOR SE",
    price: 190,
    isVeg: true,
    isBestSeller: false,
    rating: 4.4,
    reviewsCount: 55,
    imageUrl: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&q=80&w=600",
    description: "Delightful vegetarian patties made of spinach, mashed potatoes, green peas and ground native tandoor herbs.",
    prepTime: "12 mins"
  },
  {
    id: "t3",
    name: "Tandoori Momo",
    category: "TANDOOR SE",
    price: 160,
    isVeg: true,
    isBestSeller: true,
    rating: 4.7,
    reviewsCount: 139,
    imageUrl: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&q=80&w=600",
    description: "Steamed vegetable dumplings coated in high-heat tandoori spices and charred over authentic red hot coals.",
    prepTime: "15 mins"
  },
  {
    id: "t4",
    name: "Soya Chaap Tikka",
    category: "TANDOOR SE",
    price: 220,
    isVeg: true,
    isBestSeller: false,
    rating: 4.5,
    reviewsCount: 78,
    imageUrl: "https://images.unsplash.com/photo-1585938338392-50a59970d2ee?auto=format&fit=crop&q=80&w=600",
    description: "Juicy, spiced soybean sticks smoked inside the traditional clay oven tandoor with fresh lime butter zest.",
    prepTime: "15 mins"
  },

  // 4. APPETIZERS
  {
    id: "a1",
    name: "Veg Pakoda",
    category: "APPETIZERS",
    price: 120,
    isVeg: true,
    isBestSeller: false,
    rating: 4.3,
    reviewsCount: 44,
    imageUrl: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&q=80&w=600",
    description: "Crispy fritters composed of sliced farm cabbage, onions, potatoes, spinach, bound by golden chickpea dust.",
    prepTime: "10 mins"
  },
  {
    id: "a2",
    name: "Paneer Pakoda",
    category: "APPETIZERS",
    price: 160,
    isVeg: true,
    isBestSeller: false,
    rating: 4.5,
    reviewsCount: 67,
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=600",
    description: "Fluffy paneer slice sandwiches spiced with green mint compote, dipped in light chickpea shell and deep fried.",
    prepTime: "10 mins"
  },
  {
    id: "a3",
    name: "French Fries",
    category: "APPETIZERS",
    price: 110,
    isVeg: true,
    isBestSeller: false,
    rating: 4.4,
    reviewsCount: 89,
    imageUrl: "https://images.unsplash.com/photo-1576107232684-1279f390859f?auto=format&fit=crop&q=80&w=600",
    description: "Classic golden steakhouse-cut salted crispy fries, served piping hot with premium tomato chili dips.",
    prepTime: "8 mins"
  },

  // 5. SOUP
  {
    id: "s1",
    name: "Hot & Sour Soup",
    category: "SOUP",
    price: 90,
    isVeg: true,
    isBestSeller: false,
    rating: 4.3,
    reviewsCount: 51,
    imageUrl: "https://images.unsplash.com/photo-1547592165-e1d17fed6005?auto=format&fit=crop&q=80&w=600",
    description: "Comforting peppery vegetable broth balanced with absolute dark vinegar sauce and rich white pepper spice.",
    prepTime: "10 mins"
  },
  {
    id: "s2",
    name: "Veg Manchow Soup",
    category: "SOUP",
    price: 90,
    isVeg: true,
    isBestSeller: true,
    rating: 4.6,
    reviewsCount: 110,
    imageUrl: "https://images.unsplash.com/photo-1547592165-e1d17fed6005?auto=format&fit=crop&q=80&w=600",
    description: "Bold garlic ginger infused Indo-Chinese classic, packed with shredded crisp greens, topped with crispy fried noodles.",
    prepTime: "10 mins"
  },

  // 6. BEVERAGES
  {
    id: "b1",
    name: "Mineral Water",
    category: "BEVERAGES",
    price: 20,
    isVeg: true,
    isBestSeller: false,
    rating: 4.9,
    reviewsCount: 300,
    imageUrl: "https://images.unsplash.com/photo-1608885898957-a599ff15b841?auto=format&fit=crop&q=80&w=600",
    description: "Chilled pure mineral water bottle for high-end crisp clean hydration.",
    prepTime: "2 mins"
  },
  {
    id: "b2",
    name: "Coke",
    category: "BEVERAGES",
    price: 30,
    isVeg: true,
    isBestSeller: false,
    rating: 4.8,
    reviewsCount: 220,
    imageUrl: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=600",
    description: "Chilled Coca-Cola carbonated beverage can, served in glass.",
    prepTime: "2 mins"
  },
  {
    id: "b3",
    name: "Fanta",
    category: "BEVERAGES",
    price: 30,
    isVeg: true,
    isBestSeller: false,
    rating: 4.7,
    reviewsCount: 95,
    imageUrl: "https://images.unsplash.com/photo-1624552184280-9e9631627974?auto=format&fit=crop&q=80&w=600",
    description: "Chilled bright sweet orange flavored bubbly beverage.",
    prepTime: "2 mins"
  },
  {
    id: "b4",
    name: "Mazza",
    category: "BEVERAGES",
    price: 30,
    isVeg: true,
    isBestSeller: false,
    rating: 4.8,
    reviewsCount: 130,
    imageUrl: "https://images.unsplash.com/photo-1527029016493-a54a25e3d1f1?auto=format&fit=crop&q=80&w=600",
    description: "Sweet golden mango nectar beverage, chilled and super thick.",
    prepTime: "2 mins"
  },
  {
    id: "b5",
    name: "Sting",
    category: "BEVERAGES",
    price: 30,
    isVeg: true,
    isBestSeller: false,
    rating: 4.5,
    reviewsCount: 140,
    imageUrl: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=600",
    description: "Premium high energy sweet strawberry ginseng kick drink.",
    prepTime: "2 mins"
  },
  {
    id: "b6",
    name: "Sweet Lassi (Bawarchi Special)",
    category: "BEVERAGES",
    price: 30,
    isVeg: true,
    isBestSeller: true,
    rating: 4.9,
    reviewsCount: 215,
    imageUrl: "https://images.unsplash.com/photo-1571115177098-24ec4209350a?auto=format&fit=crop&q=80&w=600",
    description: "Traditional sweet whipped thick curd beverage garnished with rose water, cardamoms, sliced nuts.",
    prepTime: "5 mins"
  },
  {
    id: "b7",
    name: "Masala Coke",
    category: "BEVERAGES",
    price: 50,
    isVeg: true,
    isBestSeller: true,
    rating: 4.7,
    reviewsCount: 88,
    imageUrl: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=600",
    description: "Chilled Coca Cola spiced with raw rock salt, native lime extract, roasted cumin zest.",
    prepTime: "3 mins"
  },

  // 7. MOMOS
  {
    id: "m1",
    name: "Veg Momo",
    category: "MOMOS",
    price: 70,
    isVeg: true,
    isBestSeller: false,
    rating: 4.5,
    reviewsCount: 120,
    imageUrl: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&q=80&w=600",
    description: "Soft steamed native dumplings filled with hand-shredded fresh cabbage, carrots, onions, ginger hints.",
    prepTime: "12 mins"
  },
  {
    id: "m2",
    name: "Fry Momo",
    category: "MOMOS",
    price: 90,
    isVeg: true,
    isBestSeller: false,
    rating: 4.6,
    reviewsCount: 110,
    imageUrl: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&q=80&w=600",
    description: "Our core vegetable dumplings fried to a light gold crust, crunchy shell and juicy, spiced filling.",
    prepTime: "12 mins"
  },
  {
    id: "m3",
    name: "Chilly Momo",
    category: "MOMOS",
    price: 140,
    isVeg: true,
    isBestSeller: true,
    rating: 4.8,
    reviewsCount: 165,
    imageUrl: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&q=80&w=600",
    description: "Fried momos tossed together with crisp bell peppers, onions, spicy red chili glaze, hot soy seasonings.",
    prepTime: "15 mins"
  },
  {
    id: "m4",
    name: "Jhol Momo",
    category: "MOMOS",
    price: 150,
    isVeg: true,
    isBestSeller: true,
    rating: 4.9,
    reviewsCount: 98,
    imageUrl: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&q=80&w=600",
    description: "Traditional Nepalese style momo drowned in a rich, tangy sesame tomato soup base packed with roasted herbs.",
    prepTime: "15 mins"
  },
  {
    id: "m5",
    name: "Sizzler Momo",
    category: "MOMOS",
    price: 170,
    isVeg: true,
    isBestSeller: true,
    rating: 4.9,
    reviewsCount: 115,
    imageUrl: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&q=80&w=600",
    description: "Extremely high temperature sizzler cast iron tray serving pan-fried momos in sweet-sour smoky gravy, hot cabbage fumes.",
    prepTime: "17 mins"
  },

  // 8. CHILLY SPECIALS
  {
    id: "c1",
    name: "Baby Corn Crispy",
    category: "CHILLY SPECIALS",
    price: 220,
    isVeg: true,
    isBestSeller: false,
    rating: 4.4,
    reviewsCount: 63,
    imageUrl: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&q=80&w=600",
    description: "Extremely crunchy deep-fried premium baby corn slices coated with a sweet & savory chili marinade.",
    prepTime: "12 mins"
  },
  {
    id: "c2",
    name: "Baby Corn Chilly",
    category: "CHILLY SPECIALS",
    price: 220,
    isVeg: true,
    isBestSeller: false,
    rating: 4.5,
    reviewsCount: 52,
    imageUrl: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&q=80&w=600",
    description: "Deep fried baby corn stir-fried in a rich, sizzling sauce of green chilies, dynamic garlic, and soy onion paste.",
    prepTime: "12 mins"
  },
  {
    id: "c3",
    name: "Chilly Potato",
    category: "CHILLY SPECIALS",
    price: 150,
    isVeg: true,
    isBestSeller: false,
    rating: 4.2,
    reviewsCount: 78,
    imageUrl: "https://images.unsplash.com/photo-1518013431117-eb1465fa5752?auto=format&fit=crop&q=80&w=600",
    description: "Crispy fried rustic potato wedges tossed inside our tangy sesame-soy hot pepper glaze.",
    prepTime: "10 mins"
  },
  {
    id: "c4",
    name: "Honey Potato",
    category: "CHILLY SPECIALS",
    price: 140,
    isVeg: true,
    isBestSeller: false,
    rating: 4.3,
    reviewsCount: 88,
    imageUrl: "https://images.unsplash.com/photo-1518013431117-eb1465fa5752?auto=format&fit=crop&q=80&w=600",
    description: "Golden glazed potato fingers dressed with light farm honey, subtle green chilies, roasted hot sesame seeds.",
    prepTime: "10 mins"
  },
  {
    id: "c5",
    name: "Crispy Potato",
    category: "CHILLY SPECIALS",
    price: 140,
    isVeg: true,
    isBestSeller: false,
    rating: 4.3,
    reviewsCount: 49,
    imageUrl: "https://images.unsplash.com/photo-1518013431117-eb1465fa5752?auto=format&fit=crop&q=80&w=600",
    description: "Super light double cooked potato matchsticks, seasoned with dry spices, fried crisp, hot and salt.",
    prepTime: "10 mins"
  },
  {
    id: "c6",
    name: "Paneer Chilly",
    category: "CHILLY SPECIALS",
    price: 220,
    isVeg: true,
    isBestSeller: true,
    rating: 4.8,
    reviewsCount: 198,
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=600",
    description: "Juicy, batter-fried cottage cheese tossed high with vibrant bell peppers, onions, szechuan sauce and raw green chilies.",
    prepTime: "15 mins"
  },
  {
    id: "c7",
    name: "Paneer 65",
    category: "CHILLY SPECIALS",
    price: 210,
    isVeg: true,
    isBestSeller: true,
    rating: 4.7,
    reviewsCount: 114,
    imageUrl: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=600",
    description: "Crispy South Indian styled tempered paneer packed with curry leaves, crushed hot pepper seeds, dry curds.",
    prepTime: "15 mins"
  },
  {
    id: "c8",
    name: "Mushroom Chilly",
    category: "CHILLY SPECIALS",
    price: 220,
    isVeg: true,
    isBestSeller: false,
    rating: 4.5,
    reviewsCount: 71,
    imageUrl: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&q=80&w=600",
    description: "Gently glazed fried fresh mushrooms flipped inside dark hot garlic soya sauce backdrop, sliced spring springers.",
    prepTime: "14 mins"
  },
  {
    id: "c9",
    name: "Veg Manchurian",
    category: "CHILLY SPECIALS",
    price: 180,
    isVeg: true,
    isBestSeller: true,
    rating: 4.6,
    reviewsCount: 132,
    imageUrl: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&q=80&w=600",
    description: "Delicious vegetable dumplings styled with fresh shredded carrots & beans, simmered in a dark soy ginger sauce pool.",
    prepTime: "12 mins"
  },

  // 9. NOODLES
  {
    id: "n1",
    name: "Classic Veg Chowmein",
    category: "NOODLES",
    price: 120,
    isVeg: true,
    isBestSeller: true,
    rating: 4.6,
    reviewsCount: 189,
    imageUrl: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&q=80&w=600",
    description: "Traditional thin wok-fried street style noodles loaded with fresh capsicums, onions, green chilies and dark soya dust.",
    prepTime: "10 mins"
  },
  {
    id: "n2",
    name: "Paneer Chowmein",
    category: "NOODLES",
    price: 140,
    isVeg: true,
    isBestSeller: false,
    rating: 4.5,
    reviewsCount: 94,
    imageUrl: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&q=80&w=600",
    description: "Classic pan noodles topped with sautéed cottage cheese ribbons and savory spiced Chinese white butter.",
    prepTime: "11 mins"
  },
  {
    id: "n3",
    name: "Schezwan Noodles",
    category: "NOODLES",
    price: 140,
    isVeg: true,
    isBestSeller: true,
    rating: 4.7,
    reviewsCount: 118,
    imageUrl: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&q=80&w=600",
    description: "Super hot fiery wok stir-fried noodles tossed inside our red chili, dynamic sichuan pepper crust oil.",
    prepTime: "10 mins"
  },
  {
    id: "n4",
    name: "Veg Sizzler Noodles",
    category: "NOODLES",
    price: 200,
    isVeg: true,
    isBestSeller: true,
    rating: 4.9,
    reviewsCount: 77,
    imageUrl: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&q=80&w=600",
    description: "Sizzling high temperature dynamic wok noodles served over bed of fresh cabbage, smoking sweet sauces.",
    prepTime: "15 mins"
  },
  {
    id: "n5",
    name: "Veg Mix Noodles",
    category: "NOODLES",
    price: 160,
    isVeg: true,
    isBestSeller: false,
    rating: 4.4,
    reviewsCount: 62,
    imageUrl: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&q=80&w=600",
    description: "Rich noodles with multiple seasonal vegetables, mushroom bits, baby corn slices and dynamic seasoning.",
    prepTime: "12 mins"
  },

  // 10. RICE
  {
    id: "r1",
    name: "Steam Basmati Rice",
    category: "RICE",
    price: 70,
    isVeg: true,
    isBestSeller: false,
    rating: 4.4,
    reviewsCount: 93,
    imageUrl: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&q=80&w=600",
    description: "Plump, premium double-polished long grain Basmati rice grains cooked fluffy.",
    prepTime: "10 mins"
  },
  {
    id: "r2",
    name: "Jeera Rice",
    category: "RICE",
    price: 100,
    isVeg: true,
    isBestSeller: false,
    rating: 4.6,
    reviewsCount: 114,
    imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=600",
    description: "Fragrant long grain fluffy rice tossed lightly in pure cow ghee and golden dry roasted cumin seeds.",
    prepTime: "10 mins"
  },
  {
    id: "r3",
    name: "Fried Rice",
    category: "RICE",
    price: 130,
    isVeg: true,
    isBestSeller: false,
    rating: 4.5,
    reviewsCount: 145,
    imageUrl: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&q=80&w=600",
    description: "Authentic high wok-heated stir-fried garlic rice combined with hand julienned crunchy garden vegetables and light vinegar.",
    prepTime: "11 mins"
  },
  {
    id: "r4",
    name: "Road Pulao (Rustic Special)",
    category: "RICE",
    price: 150,
    isVeg: true,
    isBestSeller: true,
    rating: 4.8,
    reviewsCount: 122,
    imageUrl: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&q=80&w=600",
    description: "Rich Bihari styled countryside pot-cooked pulao with pure aromatic spices, raisins, and golden fried onions.",
    prepTime: "15 mins"
  },
  {
    id: "r5",
    name: "Green Peas Pulao",
    category: "RICE",
    price: 140,
    isVeg: true,
    isBestSeller: false,
    rating: 4.4,
    reviewsCount: 51,
    imageUrl: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&q=80&w=600",
    description: "Light sweet long grain Basmati rice tossed with garden green peas, finished with pure ghee.",
    prepTime: "12 mins"
  },

  // 11. DAL
  {
    id: "d1",
    name: "Dal Fry",
    category: "DAL",
    price: 100,
    isVeg: true,
    isBestSeller: false,
    rating: 4.4,
    reviewsCount: 108,
    imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=600",
    description: "Comfort yellow lentils boiled, cream fried with ripe red tomatoes and whole cumin seeds.",
    prepTime: "10 mins"
  },
  {
    id: "d2",
    name: "Yellow Dal Tadka",
    category: "DAL",
    price: 140,
    isVeg: true,
    isBestSeller: true,
    rating: 4.7,
    reviewsCount: 154,
    imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=600",
    description: "Freshly boiled golden yellow mung split lentils with garlic, red dry chilies, pure mustard oil tadka.",
    prepTime: "10 mins"
  },
  {
    id: "d3",
    name: "Dal Makhani (Bawarchi Heritage)",
    category: "DAL",
    price: 170,
    isVeg: true,
    isBestSeller: true,
    rating: 4.9,
    reviewsCount: 290,
    imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=600",
    description: "Whole black urad dal and red kidney beans slow-simmered for 18 hours in clay tandoor furnaces with butter and fresh cream.",
    prepTime: "15 mins"
  },
  {
    id: "d4",
    name: "Black Dal Tadka",
    category: "DAL",
    price: 170,
    isVeg: true,
    isBestSeller: false,
    rating: 4.5,
    reviewsCount: 68,
    imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=600",
    description: "Delicious rich black lentils treated with high fire garlic tadka and ghee.",
    prepTime: "12 mins"
  },

  // 12. ROTI & NAAN
  {
    id: "rt1",
    name: "Tandoori Roti",
    category: "ROTI & NAAN",
    price: 15,
    isVeg: true,
    isBestSeller: false,
    rating: 4.5,
    reviewsCount: 130,
    imageUrl: "https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?auto=format&fit=crop&q=80&w=600",
    description: "Traditional whole wheat crisp bread, charred in clay oven tandoors.",
    prepTime: "4 mins"
  },
  {
    id: "rt2",
    name: "Butter Tandoori Roti",
    category: "ROTI & NAAN",
    price: 20,
    isVeg: true,
    isBestSeller: false,
    rating: 4.6,
    reviewsCount: 198,
    imageUrl: "https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?auto=format&fit=crop&q=80&w=600",
    description: "Wheat traditional flatbread roasted over coals, slathered with pure melted cows butter.",
    prepTime: "4 mins"
  },
  {
    id: "rt3",
    name: "Plain Naan",
    category: "ROTI & NAAN",
    price: 35,
    isVeg: true,
    isBestSeller: false,
    rating: 4.4,
    reviewsCount: 74,
    imageUrl: "https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?auto=format&fit=crop&q=80&w=600",
    description: "Ultra fluffy soft refined flour yeast bread, stretched manually and stuck to tandoor interior wall.",
    prepTime: "5 mins"
  },
  {
    id: "rt4",
    name: "Butter Naan",
    category: "ROTI & NAAN",
    price: 45,
    isVeg: true,
    isBestSeller: true,
    rating: 4.8,
    reviewsCount: 310,
    imageUrl: "https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?auto=format&fit=crop&q=80&w=600",
    description: "Classic multi-layered highly flaked premium soft naan brushed generously with hot liquid country butter.",
    prepTime: "5 mins"
  },
  {
    id: "rt5",
    name: "Garlic Naan",
    category: "ROTI & NAAN",
    price: 60,
    isVeg: true,
    isBestSeller: true,
    rating: 4.9,
    reviewsCount: 220,
    imageUrl: "https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?auto=format&fit=crop&q=80&w=600",
    description: "Exquisite clay-baked naan bread, seasoned with heavily roasted minced garlic bits and dynamic fresh coriander greens.",
    prepTime: "6 mins"
  },
  {
    id: "rt6",
    name: "Amritsari Kulcha",
    category: "ROTI & NAAN",
    price: 60,
    isVeg: true,
    isBestSeller: false,
    rating: 4.6,
    reviewsCount: 95,
    imageUrl: "https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?auto=format&fit=crop&q=80&w=600",
    description: "Yeast bread stuffed with seasoned mashed crisp potatoes, onions, carom spices, flat charred.",
    prepTime: "6 mins"
  },
  {
    id: "rt7",
    name: "Cheese Naan",
    category: "ROTI & NAAN",
    price: 80,
    isVeg: true,
    isBestSeller: true,
    rating: 4.9,
    reviewsCount: 180,
    imageUrl: "https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?auto=format&fit=crop&q=80&w=600",
    description: "Premium bread envelopes filled deep with pure grated cheddar and mozzarella, baked soft, absolutely pullable.",
    prepTime: "7 mins"
  }
];

export const SPECIAL_OFFERS: SpecialOffer[] = [
  {
    id: "o1",
    title: "18-Hour Dal Makhani Ritual",
    subtitle: "Get free Butter Naan on checkout today",
    discountCode: "BAWARCHILOVE",
    discountText: "FREE NAAN",
    imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=600",
    bannerColor: "from-orange-600 via-amber-600 to-red-600"
  },
  {
    id: "o2",
    title: "The Royal Midnight Shahi Paneer",
    subtitle: "Flat 15% discount on orders above ₹600",
    discountCode: "ROYAL15",
    discountText: "15% OFF",
    imageUrl: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=600",
    bannerColor: "from-neutral-900 via-amber-950 to-neutral-900"
  },
  {
    id: "o3",
    title: "Royal Indian Special Celebration Thali",
    subtitle: "Complimentary elite Sweet Lassi with every Thali",
    discountCode: "LASSITHALI",
    discountText: "FREE LASSI",
    imageUrl: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&q=80&w=600",
    bannerColor: "from-orange-950 via-amber-700 to-rose-950"
  }
];

export const CUSTOMER_REVIEWS: Review[] = [
  {
    id: "r1",
    name: "Aditya Narayan Pathak",
    rating: 5,
    comment: "Spicy Bawarchi has completely elevated the dining scene in Forbesganj. The Butter Naan and Paneer Tikka Masala are pure masterpieces. Exceptional premium presentation!",
    date: "28 May 2026",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200"
  },
  {
    id: "r2",
    name: "Divya Mishra",
    rating: 5,
    comment: "The Jhol Momos and Special Thali are incredibly tasty. It looks and tastes like a 5-star restaurant. Super quick service at our tables!",
    date: "15 May 2026",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200"
  },
  {
    id: "r3",
    name: "Rishi Raj",
    rating: 5,
    comment: "I booked a family anniversary event here and everything was seamless. High level food startup vibes. Direct table QR ordering is flawless.",
    date: "10 May 2026",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200"
  }
];

export const QUICK_CATEGORIES = [
  { name: "VEGETABLES", displayName: "Vegetables", count: 21 },
  { name: "SPECIAL THALI", displayName: "Special Thali", count: 1 },
  { name: "MOMOS", displayName: "Momos", count: 5 },
  { name: "NOODLES", displayName: "Noodles", count: 5 },
  { name: "RICE", displayName: "Rice", count: 5 },
  { name: "DAL", displayName: "Dal & Curry", count: 4 },
  { name: "ROTI & NAAN", displayName: "Roti & Naan", count: 7 },
  { name: "BEVERAGES", displayName: "Beverages", count: 7 },
  { name: "TANDOOR SE", displayName: "Tandoose Sizzlers", count: 4 },
  { name: "APPETIZERS", displayName: "Appetizers", count: 3 },
  { name: "SOUP", displayName: "Soups", count: 2 },
  { name: "CHILLY SPECIALS", displayName: "Chilly Specials", count: 9 }
];

export const GALLERY_ITEMS = [
  { url: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&q=80&w=400", title: "Rich Creamy Paneer Butter Masala" },
  { url: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&q=80&w=400", title: "Bawarchi Special Thali Premium Presentation" },
  { url: "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=400", title: "Tandoori Specialties Grilled Live" },
  { url: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&q=80&w=400", title: "Signature Steamed & Fried Spicy Momos" },
  { url: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&q=80&w=400", title: "Wok Hot Spicy Chef Special Chowmein" },
  { url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=400", title: "Slow Simmered Heritage Dal Makhani" }
];
